---
###### Routing Groups ######
eigrp:
  data:
    routing: eigrp
ospf:
  data:
    routing: ospf
rip:
  data:
    routing: rip
bgp:
  data:
    routing: bgp
ibgp:
  data:
    routing: ibgp
###### Platform Groups ######
ios:
  platform: ios
  connection_options:
    netmiko:
      platform: cisco_ios
      extras: {}
    napalm:
      extras:
        optional_args: {}

nxos:
  platform: nxos
  connection_options:
    netmiko:
      platform: cisco_nxos
      extras: {}
    napalm:
      port: 8443
      extras:
        optional_args: {}

xr:
  platform: xr
  connection_options:
    netmiko:
      platform: cisco_xr
      extras: {}
    napalm:
      port: 8443
      extras:
        optional_args: {}